language: ruby
rvm:
  - 2.4.2
before_install:
  - gem update --system
  - gem install bundler 

script: bundle exec jekyll build
sudo: false
exclude: [vendor]
cache: bundler

after_success:
  - git remote add deploy frank@82.196.4.177:repo/microblog
  - git push deploy